name: Version Request
description: Request support for a specific Minecraft version.
labels:
  - version request
body:
  - type: input
    id: requested-version
    attributes:
      label: Requested Version
      description: Which Minecraft version do you want us to support?
      placeholder: 1.20.1
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Why do you need this specific version?
      placeholder: I play on a server that hasn't updated yet...
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting your request.
      options:
        - label: >-
            I have checked the latest release and confirmed this version is not
            currently supported.
          required: true
        - label: >-
            This version hasn't been requested already (I have searched existing
            issues on GitHub).
          required: true